### ISSUE TITLE
Nusselt values of NaN

### ISSUE THREAD

**Issue by michaelneuder** [dsondak/optRBC#12]
We are finding that some values of the grid parameters lead to NaN values of Nusselt. https://github.com/dsondak/optRBC/pull/11 demonstrates this with a small example. In this case Nx=1600 and Ny=2500. Over a time of 5 seconds with dt = 0.1 seconds, the last 7 times steps show a NaN nusselt value. The output of this looks like

```
 Computing Nu...
 Nu =    2.8746606257045642
 time =    4.3000000000000007      dt =   0.10000000000000001
 Computing Nu...
 Nu =    1215.8309264426352
 time =    4.4000000000000004      dt =   0.10000000000000001
 Computing Nu...
 Nu =                        NaN
 time =    4.5000000000000000      dt =   0.10000000000000001
 Computing Nu...
 Nu =                        NaN
 time =    4.5999999999999996      dt =   0.10000000000000001
 Computing Nu...
 Nu =                        NaN
 time =    4.6999999999999993      dt =   0.10000000000000001
 Computing Nu...
 Nu =                        NaN
 time =    4.7999999999999989      dt =   0.10000000000000001
 Computing Nu...
 Nu =                        NaN
 time =    4.8999999999999986      dt =   0.10000000000000001
 Computing Nu...
 Nu =                        NaN
 time =    4.9999999999999982      dt =   0.10000000000000001
 Computing Nu...
 Nu =                        NaN
 time =    5.0000000000000000      dt =   0.10000000000000001
```

**Comment by dsondak** [comment]
@michaelneuder This is likely because you need to make the time step smaller. In explicit methods, the time step and spatial discretization are connected through a parameter called the CFL number. This code is partial implicit and partial explicit, so it will still have some time step restrictions. There is a subroutine in time_integrators.f90 that will adapt the time step for you. But for now you can just try with a dt = 0.01 and integrate out to the same point.

**Comment by michaelneuder** [comment]
Ok, great thanks! I recalled that we discussed that higher Ra numbers needed smaller time steps, but I didn't realize that if we kept the Ra number fixed and just increased the grid we would also need more time steps. This is great info!
